# Generated by Django 3.2.3 on 2023-05-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_currency', models.CharField(max_length=10)),
                ('bought_currency', models.CharField(max_length=10)),
                ('sold_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bought_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('market_rate_other', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exchange_direction', models.CharField(choices=[('S', 'Sold'), ('B', 'Bought')], max_length=1)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
