# Generated by Django 3.2.3 on 2023-06-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='bought_amount',
            new_name='coin_rate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='sold_amount',
            new_name='dollar_rate',
        ),
    ]
