# Generated by Django 3.2.3 on 2023-06-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20230604_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsdToCzk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.CharField(max_length=5)),
                ('czk', models.CharField(max_length=5)),
                ('usd_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('czk_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rate',
            name='coin_rate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='rate',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
