# Generated by Django 3.2.3 on 2023-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_auto_20230606_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdtoczk',
            name='czk_rate',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
    ]
