# Generated by Django 3.2.3 on 2023-06-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_alter_usdtoczk_czk_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='coin_rate',
            field=models.DecimalField(decimal_places=10, max_digits=64),
        ),
        migrations.AlterField(
            model_name='rate',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=10, max_digits=64),
        ),
        migrations.AlterField(
            model_name='usdtoczk',
            name='czk_rate',
            field=models.DecimalField(decimal_places=10, max_digits=64),
        ),
    ]
