# Generated by Django 3.2.3 on 2023-06-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_auto_20230607_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='coin_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='dollar_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='market_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='market_rate_other',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usdtoczk',
            name='czk_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usdtoczk',
            name='usd_rate',
            field=models.FloatField(),
        ),
    ]
