# Generated by Django 3.2.3 on 2023-06-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_auto_20230611_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='image',
            field=models.ImageField(default=1, upload_to='icons_coin/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='round_num',
            field=models.IntegerField(default=0),
        ),
    ]
