# Generated by Django 3.2.3 on 2023-07-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0008_auto_20230620_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icons_coin/'),
        ),
    ]
