# Generated by Django 3.2.3 on 2023-05-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transactionrequest',
            name='surname',
        ),
    ]
