# Generated by Django 3.2.3 on 2023-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20230524_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='transaction_id',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
