# Generated by Django 3.2.3 on 2023-05-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_transactionrequest_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
