# Generated by Django 3.2.3 on 2023-05-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transactionrequest_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
