# Generated by Django 3.2.3 on 2023-06-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_transactionrequest_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='faktura',
            field=models.FileField(blank=True, null=True, upload_to='order/sold/'),
        ),
        migrations.AddField(
            model_name='transactionrequest',
            name='pokladni',
            field=models.FileField(blank=True, null=True, upload_to='order/sold/'),
        ),
        migrations.AddField(
            model_name='transactionrequest',
            name='vydana',
            field=models.FileField(blank=True, null=True, upload_to='order/bought/'),
        ),
    ]
