# Generated by Django 3.2.3 on 2023-06-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20230607_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrequest',
            name='bought_amount',
            field=models.DecimalField(decimal_places=30, max_digits=64, verbose_name='Bought amount'),
        ),
    ]
