# Generated by Django 4.2.2 on 2023-07-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20230611_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrequest',
            name='processed',
        ),
    ]
