# Generated by Django 4.2.2 on 2023-07-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_transactionrequest_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionrequest',
            old_name='processed',
            new_name='processed_transaction',
        ),
    ]
