# Generated by Django 4.2.2 on 2023-07-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_rename_processed_transactionrequest_processed_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionrequest',
            old_name='processed_transaction',
            new_name='processed',
        ),
    ]
