# Generated by Django 3.2.3 on 2023-05-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fo',
            name='address_residence',
            field=models.TextField(blank=True, null=True, verbose_name='Exact address and country residence'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The authority that issued'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='birth_number',
            field=models.CharField(blank=True, choices=[('A', 'allocated'), ('U', 'unassigned')], max_length=1, verbose_name='Birth number'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='client_acts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blank.clientacts', verbose_name='The client acts as the person engaged in business'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='client_legal_entity',
            field=models.CharField(blank=True, choices=[('S', 'Statutor'), ('P', 'power of attorney'), ('O', 'Ohter')], max_length=1, verbose_name='The client is legal entity'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='fo',
            name='date_of_validity_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of validity from'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='date_of_validity_until',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of validity until'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='indetity_card_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indetity card number'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='internal_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Internal identifier'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='nationality',
            field=models.TextField(blank=True, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='place_birth',
            field=models.TextField(blank=True, null=True, verbose_name='Place and country birth'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='type_id_card',
            field=models.CharField(blank=True, choices=[('P', 'passport'), ('I', 'ID card'), ('D', 'driving licence'), ('R', 'residence permit'), ('O', 'other ID')], max_length=1, verbose_name='Type of ID card'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blank.worker', verbose_name='He made the identification'),
        ),
    ]
