# Generated by Django 3.2.3 on 2023-06-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0004_auto_20230531_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientacts',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The exact address of the register office, including the state:'),
        ),
        migrations.AlterField(
            model_name='clientacts',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business name:'),
        ),
        migrations.AlterField(
            model_name='clientacts',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id:'),
        ),
    ]
