# Generated by Django 3.2.3 on 2023-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0008_alter_fo_client_acts'),
    ]

    operations = [
        migrations.AddField(
            model_name='fo',
            name='skan_person',
            field=models.FileField(blank=True, null=True, upload_to='document_fo_person/'),
        ),
    ]
