# Generated by Django 3.2.3 on 2023-07-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0009_fo_skan_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='fo',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
